### ISSUE TITLE
Metadata Items not reflecting property types: title-type and display-seq

### ISSUE THREAD

**Issue by majora2007** [vers-one/EpubReader#81] opened 2023-05-03 13:28 UTC
`epubBook.Schema.Package.Metadata.MetaItems` does not seem to be showing "title-type" or "display-seq", which limits the ability to use `dc:title` tags for grouping books into collections/reading lists. 

See the following:
```    
<dc:title id="t3">The New French Cuisine Masters</dc:title>
<meta refines="#t3" property="title-type">collection</meta>
<meta refines="#t3" property="display-seq">3</meta>
```

https://www.w3.org/publishing/epub3/epub-packages.html#sec-title-type

When I run:
` epubBook.Schema.Package.Metadata.MetaItems.Select(item => item.Property)`

![image](https://user-images.githubusercontent.com/735851/235929685-58f2d57e-6fd0-4883-b6fb-d467c0fe4827.png)

**Comment by vers-one** [comment] 2023-05-03 13:38
Hmm, I can't reproduce this. I see both of those properties in `EpubBook.Schema.Package.Metadata.MetaItems` when I test the snippet from your message:
![image](https://user-images.githubusercontent.com/12114169/235932561-a48903ef-5161-4058-ba4d-1f4d9357a212.png)

**Comment by majora2007** [comment] 2023-05-03 20:27
Hmm, okay I do see them on a second opening of the epub, first open it's empty. I'll investigate that as it might be with my code, however, now I have another issue. 

The `title-type` refines a dc:title, but that doesn't show on MetadataItems. There is Metadata.Titles which has the string, but doesn't have the id, so it's impossible to find the title this metadata item refines. 

Is there a reason why the Titles don't appear on MetadataItems?

**Comment by vers-one** [comment] 2023-05-03 20:58
[`EpubBook.Schema.Package.Metadata.MetaItems`](https://os.vers.one/EpubReader/reference/VersOne.Epub.Schema.EpubMetadata.html#VersOne_Epub_Schema_EpubMetadata_MetaItems) collection contains only `package/metadata/meta` XML elements. The content of the `package/metadata/dc:title` XML elements is available through the [`EpubBook.Schema.Package.Metadata.Titles`](https://os.vers.one/EpubReader/reference/VersOne.Epub.Schema.EpubMetadata.html#VersOne_Epub_Schema_EpubMetadata_Titles) property.

I wrote this implementation long before EPUB 3 specification was released. In EPUB 2 `<dc:title>` elements didn't have any attributes, so it was reasonable to use `List<string>` type to represent this data. EPUB 3 added `id`, `dir`, and `xml:lang` attributes but at that time it was already too late to add them without breaking compatibility with the previous versions of EpubReader. That's also the reason why some other metadata types are missing `id` and `xml:lang` properties. However, I do plan to go through all schema types and add missing attributes in the future.

**Comment by majora2007** [comment] 2023-05-03 23:10
Ahhh I see. Hmm, okay, then it looks like my story is blocked until that time. If there is anything I can do to help you with your implementation goals, let me know. My application relies on your library for all things epub.

**Comment by vers-one** [comment] 2023-05-04 00:03
I added https://github.com/vers-one/EpubReader/issues/82 to track this work.

I will probably split the Media Overlays feature into two parts, push the remaining work into the 3.3.1 release, and add the missing schema properties in 3.3.0 instead. That way the breaking changes will be in 3.3.0 minor release instead of 3.3.1 patch release.

**Comment by majora2007** [comment] 2023-05-04 00:13
Awesome, that would be really helpful. On a completely unrelated note, do you have a way to accept donations? I've been meaning to ask since last year, but I wanted to give back to some of the projects that enable my application, and your library has been critical since epub support was added.

**Comment by vers-one** [comment] 2023-05-04 00:24
No, I don't. I treat this project as a hobby so just the fact that this library is useful for some people means much more to me.

**Comment by majora2007** [comment] 2023-05-04 12:48
I'm in the same boat with my project. I have 7k installs as of now and most of them use your library plus my reader to consume their epubs, so let me just give my thanks for your continued development of the library and support for the few times I've come to you.

**Comment by vers-one** [comment] 2023-05-15 23:12
All missing metadata attributes have been added in the [3.3.0 release](https://github.com/vers-one/EpubReader/releases/tag/v3.3.0).

**Closed by vers-one** 2023-05-15 23:12 UTC
